// Uses the synthetic knowledge_fixture.py server. Never point at a live database.
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(12000);
 const base=process.env.EVOLVMEM_TEST_URL||'http://127.0.0.1:39478',errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 const done=async()=>{await page.waitForLoadState('networkidle');return page.waitForFunction(()=>!document.querySelector('#content')?.inert&&document.querySelector('.knowledge-workspace')?.getAttribute('aria-busy')!=='true');};
 const go=async(hash,selector)=>{await done();await page.goto(base+'/'+hash);await page.waitForSelector(selector);await done();};
 const click=async(selector)=>{await page.locator(selector).first().click();await done();};
 const close=async()=>{await click('#dialog [data-action="close"]');};
 const consent=()=>page.once('dialog',d=>d.accept());
 try{
 await go('#home','.home-lanes');await page.waitForFunction(()=>document.querySelector('[data-stat="qa_active"]').textContent!=='—');
 assert.equal(await page.locator('.home-lane').count(),2);await click('[data-refresh]');checks.push('首页两类记忆及刷新');await page.screenshot({path:'/tmp/evo-home-final.png',fullPage:true});
 await go('#knowledge/projects','.project-grid');assert.equal(await page.locator('.project-grid h3').filter({hasText:'Evo 演示项目'}).count(),1);
 await click('[data-action="project-new"]');await page.locator('#project-id').fill('browser-project');await page.locator('#project-name').fill('浏览器验收项目');await page.locator('#project-aliases').fill('验收别名');await click('[data-action="project-save"]');await page.waitForSelector('[data-action="project-edit"][data-project="browser-project"]');
 await click('[data-action="project-edit"][data-project="browser-project"]');assert.equal(await page.locator('#project-aliases').inputValue(),'验收别名');await page.locator('#project-name').fill('验收项目');await click('[data-action="project-save"]');checks.push('项目新增、名称别名编辑、重复名称展示');
 await page.getByRole('link',{name:'Evo 演示项目',exact:true}).click();await page.waitForSelector('.memory-lanes');await click('[data-memory-lane="history"]');await page.reload();await page.waitForSelector('.project-conversations');assert.ok(page.url().includes('project=evo'));checks.push('项目和历史类型刷新保留');
 await page.locator('.signal-nav [data-knowledge-view="qa"]').click();await page.waitForSelector('#qa-project-filter');assert.equal(await page.locator('.signal-nav [aria-current="page"]').innerText(),'经验问答');
 await page.goBack();await page.waitForSelector('.project-conversations');await page.goForward();await page.waitForSelector('#qa-project-filter');checks.push('导航高亮、返回和前进');
 await page.locator('#qa-project-filter').selectOption('evo');await page.locator('#qa-category-filter').selectOption('project_convention');await page.locator('#qa-state-filter').selectOption('active');await page.locator('#qa-search').fill('验收条件');await page.locator('#qa-search').press('Enter');await done();assert.ok(await page.locator('.qa-card').count());checks.push('问答项目、分类、状态和回车搜索');
 await click('[data-memory-action="new"]');await page.locator('#qa-question').fill('测试草稿该怎样确认？');await page.locator('#qa-answer').fill('核对内容和来源后，在待确认中入库。');await page.locator('#qa-project').selectOption('browser-project');await click('[data-memory-action="draft"]');await page.waitForSelector('#qa-project-filter');
 await go('#knowledge/intake','#filter-queue');await page.getByRole('button',{name:'测试草稿该怎样确认？',exact:true}).click();await page.waitForSelector('#item-body');await click('[data-action="item-publish"]');await page.waitForFunction(()=>!document.querySelector('#dialog').open);
 await go('#knowledge/qa','#qa-project-filter');await page.locator('#qa-project-filter').selectOption('browser-project');await page.locator('#qa-state-filter').selectOption('active');await done();await page.waitForSelector('.qa-card');assert.match(await page.locator('.qa-cards').innerText(),/测试草稿/);checks.push('问答保存草稿→资料待确认→有效问答');
 await page.locator('.qa-card [data-memory-action="edit"]').first().click();await page.locator('#qa-answer').fill('尚未保存的新答案不能静默丢失。');page.once('dialog',d=>d.dismiss());await click('.memory-dialog [data-memory-action="close"]');assert.ok(await page.locator('.memory-dialog').isVisible());consent();await click('.memory-dialog [data-memory-action="close"]');checks.push('未保存问答取消保护');
 await go('#knowledge/intake','#filter-queue');await click('#new-item');await page.locator('#item-title').fill('归属与状态验收');await page.locator('#item-body').fill('浏览器验收项目的资料，必须核对内容再保存。');await page.locator('#item-project').selectOption('browser-project');await click('[data-action="create-draft"]');
 await page.getByRole('button',{name:'归属与状态验收',exact:true}).click();await page.locator('#item-project').selectOption('evo');await click('[data-action="assign"]');await page.waitForFunction(()=>document.querySelector('#item-project')?.value==='evo');await page.locator('#item-category').selectOption('environment');await page.locator('#item-trigger').fill('仅用于本地开发');await click('[data-action="classification-save"]');
 await page.locator('#item-body').fill('已纠正的环境资料仅用于本地开发。');await click('[data-action="item-save"]');await page.waitForFunction(()=>document.querySelector('#item-body')?.value.includes('已纠正'));await click('[data-action="item-publish"]');
 await go('#knowledge/library','#filter-status');await page.locator('#search').fill('归属与状态验收');await click('[data-action="search"]');await page.getByRole('button',{name:'归属与状态验收',exact:true}).click();await click('[data-action="item-archive"]');await page.locator('#filter-status').selectOption('archived');await done();await page.getByRole('button',{name:'归属与状态验收',exact:true}).click();await click('[data-action="item-restore"]');await page.locator('#filter-status').selectOption('active');await done();await page.getByRole('button',{name:'归属与状态验收',exact:true}).click();consent();await click('[data-action="item-delete"]');await page.locator('#filter-status').selectOption('deleted');await done();await page.getByRole('button',{name:'归属与状态验收',exact:true}).click();await click('[data-action="item-restore"]');checks.push('资料新增、更改归属、分类、正文编辑、入库、归档、恢复、删除与找回');
 await go('#knowledge/rules','#min-confidence');const old=await page.locator('#min-confidence').inputValue();await page.locator('#min-confidence').fill('0.99');await click('[data-rule-stage="trial"]');await page.locator('#extraction-project').selectOption('evo');await click('#extraction-preview-button');await page.waitForSelector('.extraction-comparison');assert.deepEqual(await page.locator('.extraction-candidate > .badge').allTextContents(),['自动入库','待确认']);await click('[data-rule-stage="settings"]');assert.equal(await page.locator('#min-confidence').inputValue(),'0.99');await click('[data-action="rules-save"]');await page.waitForFunction(()=>document.querySelector('#rules-save-state')?.textContent==='已保存');
 await click('[data-rule-stage="trial"]');await click('[data-rule-mode="material"]');await page.locator('#sample-title').fill('Evo 演示项目规则');await page.locator('#sample-body').fill('Evo 演示项目应保留清洗历史并保存简洁问答。');await click('[data-action="rule-preview"]');await page.waitForSelector('#preview-result');checks.push('规则草稿保留、保存、对话比较、资料判断');
 await go('#knowledge/skill','#skill-text');const skill=await page.locator('#skill-text').inputValue();await page.locator('#skill-text').fill(skill+'\n浏览器测试说明：保留来源。\n');await click('[data-action="skill-save"]');await page.waitForFunction(()=>document.querySelector('#skill-text').value.includes('浏览器测试说明'));const download=page.waitForEvent('download');await click('[data-action="skill-download"]');assert.equal((await download).suggestedFilename(),'SKILL.md');checks.push('管理 Skill 编辑保存与下载');
 await go('#knowledge/learning','#learning-project');await page.locator('#learning-project').selectOption('evo');await page.locator('#learning-family').fill('内部工具');await click('[data-learning-action="family"]');await page.waitForSelector('#learning-family');assert.equal(await page.locator('#learning-family').inputValue(),'内部工具');await click('[data-learning-action="preview"]');await page.waitForSelector('#learning-preview');assert.match(await page.locator('#learning-preview').innerText(),/协作/);
 const before=await page.locator('#learning-framework').inputValue();await page.locator('#learning-framework').fill(before+'\n浏览器验证：保存框架版本。');await click('[data-learning-action="save"]');await page.waitForFunction(()=>document.querySelector('#learning-framework').value.includes('浏览器验证'));await click('[data-learning-action="compare"]');await page.waitForSelector('#learning-preview');checks.push('项目类型、协作 Skill 预览、框架保存与版本比较');
 const options=await page.locator('#learning-version option').evaluateAll(xs=>xs.map(x=>x.value));if(options.length>1){await page.locator('#learning-version').selectOption(options[1]);consent();await click('[data-learning-action="restore"]');await page.waitForSelector('#learning-framework');}checks.push('恢复协作 Skill 历史版本');
 await page.locator('#learning-state').selectOption('candidate');await done();const candidate=page.locator('[data-learning-action="accept"]').first();if(await candidate.count()){await candidate.click();await done();checks.push('学习规则确认');}await page.locator('#learning-state').selectOption('active');await done();const reject=page.locator('[data-learning-action="reject"]').first();if(await reject.count()){await reject.click();await done();checks.push('学习规则否决');}
 await click('[data-learning-action="analyze"]');await done();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('分析'));await click('[data-learning-action="analyze-family"]');await done();checks.push('项目与同类项目分析（合成模型）');
 for(const width of [390,768,1024,1440]){await page.setViewportSize({width,height:900});for(const [hash,sel] of [['#home','.home-lanes'],['#knowledge/projects','.project-grid'],['#knowledge/qa','#qa-project-filter'],['#knowledge/intake','#filter-queue'],['#knowledge/rules','#min-confidence'],['#knowledge/learning','#learning-project'],['#progress','[data-slot="progress-browser"]'],['#experiences','[data-slot="experience-browser"]']]){await go(hash,sel);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`overflow ${width} ${hash}`);}if(width===390){await go('#knowledge/qa','#qa-project-filter');await page.screenshot({path:'/tmp/evo-workbench-mobile-final.png',fullPage:true});}}checks.push('8 个界面 × 4 种屏宽无横向溢出');
 for(const path of ['/organize','/knowledge?view=rules','/knowledge?view=skill','/legacy']){await page.goto(base+path);await page.waitForSelector('.signal-masthead');}checks.push('旧网址兼容跳转');
 await page.goto(base+'/workflow#memory-ingestion');await page.waitForFunction(()=>document.querySelector('#diagram-frame')?.dataset.ready==='true');await page.screenshot({path:'/tmp/evo-ingestion-final.png',fullPage:true});await page.locator('[data-chapter="memory-recall"]').click();await page.waitForFunction(()=>document.querySelector('#diagram-frame')?.dataset.ready==='true');await page.screenshot({path:'/tmp/evo-recall-final.png',fullPage:true});checks.push('活动图和检索流程图切换显示');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,page_errors:errors},null,2));
 }catch(error){console.error('CHECKS',checks,'TOAST',await page.locator('#toast').textContent().catch(()=>''));await page.screenshot({path:'/tmp/evo-workbench-failure.png',fullPage:true});throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
