// Real HTTP + UI against knowledge_fixture.py (synthetic data only).
const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});const qaProject='qa-'+Date.now(),caseProject='case-'+Date.now();const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);const base=process.env.EVOLVMEM_TEST_URL||'http://127.0.0.1:39478',errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const done=async()=>{await page.waitForLoadState('networkidle');await page.waitForFunction(()=>!document.querySelector('#content')?.inert&&document.querySelector('.knowledge-workspace')?.getAttribute('aria-busy')!=='true');};
const go=async(hash,selector)=>{await page.goto(base+'/'+hash);await page.waitForSelector(selector);await done();};const click=async s=>{await page.locator(s).first().click();await done();};
try{
 await go('#knowledge/qa','#qa-project-filter');await click('[data-memory-action="new"]');await page.locator('#qa-question').fill('怎样在经验中新增项目？');await page.locator('#qa-answer').fill('在问答编辑处创建项目，创建成功后自动选中。');await page.locator('[data-memory-action="project-new"]').click();await page.waitForSelector('#new-project-id');await page.locator('#new-project-id').fill(qaProject);await page.locator('#new-project-name').fill('问答内新增项目');await page.locator('#new-project-aliases').fill(qaProject+'-alias');await click('.project-create-dialog [type="submit"]');await page.waitForSelector('.project-create-dialog',{state:'detached'});assert.equal(await page.locator('#qa-project').inputValue(),qaProject);assert.equal(await page.locator('#qa-question').inputValue(),'怎样在经验中新增项目？');await click('[data-memory-action="publish"]');await go('#knowledge/projects','.project-list');assert.match(await page.locator('.project-list').innerText(),/问答内新增项目/);checks.push('问答原位新增项目、自动选中、草稿保留、入库可查');
 await go('#experiences','[data-case-project-new]');await click('[data-case-project-new]');await page.locator('#new-project-id').fill(caseProject);await page.locator('#new-project-name').fill('案例内新增项目');await click('.project-create-dialog [type="submit"]');await page.waitForSelector('.project-create-dialog',{state:'detached'});assert.equal(await page.locator('[data-slot="experience-browser"] [data-filter="project"]').inputValue(),caseProject);checks.push('经验案例原位新增项目与筛选选中');
 await go('#progress','[data-slot="progress-browser"] [data-results]');assert.equal(await page.locator('[data-progress-mode="summary"]').count(),0);assert.match(await page.locator('[data-slot="progress-browser"] [data-filter="status"]').innerText(),/全部任务/);await go('#knowledge/library?project=evo','.project-document');assert.match(await page.locator('.project-document').innerText(),/项目摘要/);await page.getByText('AI 项目摘要 · 已生成',{exact:true}).click();assert.match(await page.locator('.project-document').innerText(),/项目摘要应归入项目历史/);checks.push('任务断点只列任务，项目摘要归入历史');
 await go('#knowledge/projects','.history-tabs');assert.match(await page.locator('.history-tabs').innerText(),/已整理/);await click('.history-tabs [data-view="unassigned"]');await page.waitForSelector('#history-instructions');assert.ok((await page.locator('#history-instructions').inputValue()).length>10);
 const instructions=await page.locator('#history-instructions').inputValue();await page.locator('#history-instructions').fill(instructions+'\n演示资料按原话确认，多个项目保留待确认。');await click('[data-history-action="rules-save"]');await page.reload();await page.waitForSelector('#history-instructions');assert.match(await page.locator('#history-instructions').inputValue(),/演示资料按原话确认/);
 await page.locator('#history-select-all').check();await click('[data-history-action="preview"]');assert.match(await page.locator('#history-notice').innerText(),/尚未保存分类/);assert.equal(await page.locator('[data-history-row]').count(),3);assert.equal(await page.locator('[data-history-project]').first().inputValue(),'evo');
 await page.locator('[data-history-project]').first().selectOption('dsh-a');await click('[data-history-action="detail"]');await page.waitForSelector('.history-source-dialog');assert.match(await page.locator('.history-source-dialog').innerText(),/Evo/);await page.locator('.history-source-dialog button').click();await page.screenshot({path:'/tmp/evo-history-classification-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'history overflow 390');await page.screenshot({path:'/tmp/evo-history-classification-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await click('[data-history-action="save-all"]');assert.match(await page.locator('#history-notice').innerText(),/成功 3 条，失败 0 条/);assert.equal(await page.locator('[data-history-row]').count(),0);await click('.history-tabs [data-view="projects"]');await page.waitForSelector('.project-list');checks.push('项目历史已整理与未归属分栏，规则保存读回、真实接口 AI 预览、手动修正、批量分类、响应式页面');
 await go('#knowledge/skill','[data-pipeline-stage]');assert.equal(await page.locator('[data-pipeline-stage]').count(),3);assert.equal(await page.locator('[data-pipeline-stage="ownership"]').count(),0);assert.match(await page.locator('#content').innerText(),/项目历史/);checks.push('项目整理 Skill 移至项目历史，其他三个环节保留');
 await page.locator('#stage-instructions').fill('未保存的临时规则');page.once('dialog',d=>d.dismiss());await click('[data-pipeline-stage="ingestion"]');assert.equal(await page.locator('#stage-instructions').inputValue(),'未保存的临时规则');page.once('dialog',d=>d.accept());await click('[data-pipeline-stage="ingestion"]');checks.push('切换环节的未保存保护');
 for(const stage of ['extraction','ingestion','collaboration']){await click(`[data-pipeline-stage="${stage}"]`);assert.ok((await page.locator('#stage-instructions').inputValue()).length>10);const download=page.waitForEvent('download');await click('[data-pipeline-action="download"]');assert.equal((await download).suggestedFilename(),'SKILL.md');}checks.push('全部 Skill 可查看和下载');
 await click('[data-pipeline-stage="extraction"]');await page.locator('#stage-sample').fill('用户：我想在经验里直接加项目，不要让我到处找。');await page.locator('#stage-project').selectOption('evo');await click('[data-pipeline-action="verify"]');assert.match(await page.locator('#stage-result').innerText(),/放入待确认 [1-9]\d* 条/);checks.push('提炼 Skill 验证产出待确认问答');
 await click('[data-pipeline-stage="ingestion"]');await page.locator('#stage-sample').fill('短');await click('[data-pipeline-action="verify"]');assert.match(await page.locator('#stage-result').innerText(),/放入待确认 1 条/);checks.push('入库 Skill 验证按阈值放入待确认');
 await click('[data-pipeline-stage="collaboration"]');await page.locator('#stage-project').selectOption('evo');await click('[data-pipeline-action="verify"]');assert.match(await page.locator('#stage-result').innerText(),/分析完成|没有/);checks.push('协作 Skill 保存框架并分析验证');
 for(const path of ['/workflow','/workflow-diagram','/architecture']){await page.goto(base+path);await page.waitForSelector('.product-diagram svg');assert.ok(page.url().endsWith('#principles'));assert.equal(await page.locator('.signal-masthead').count(),1);}checks.push('原工作原理与架构地址统一进入主界面');
 for(const width of [390,768,1024,1440]){await page.setViewportSize({width,height:1000});await go('#knowledge/skill','[data-pipeline-stage]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`skill overflow ${width}`);if(width===1440)await page.screenshot({path:'/tmp/evo-skills-desktop.png',fullPage:true});await go('#principles','.product-diagram svg');for(const kind of ['modules','flow','activity']){await click(`[data-principle="${kind}"]`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${kind} overflow ${width}`);if(width===1440)await page.screenshot({path:`/tmp/evo-product-${kind}.png`,fullPage:true});}if(width===390)await page.screenshot({path:'/tmp/evo-product-mobile.png',fullPage:true});}checks.push('六模块、流程、活动图以及 Skill 页四种屏宽可用');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors},null,2));
}catch(error){await page.screenshot({path:'/tmp/evo-modules-failed.png',fullPage:true});console.error('COMPLETED',checks,'ERRORS',errors);throw error;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
