(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const types = {reference:'参考资料',fact:'事实 / 业务规则',decision:'决策',experience:'经验',playbook:'操作方法',session_summary:'会话摘要',project_summary:'项目摘要',workstream_checkpoint:'任务断点',workflow_policy:'流程规范',constraint:'约束',preference:'偏好',user_profile:'用户资料'};
  const statuses = {active:'已入库',candidate:'待确认',archived:'已归档',deleted:'已删除',superseded:'历史版本'};
  const errors = {revision_conflict:'资料已被其他操作更新，请重新打开后再保存。',project_required:'请选择所属项目，或明确选择全局知识。',project_not_found:'项目未登记，请先在项目知识库添加。',confirm_project_first:'请先确认资料归属，再确认入库。',invalid_content:'请填写标题和正文；正文最多 100,000 字。',workstream_move_confirmation_required:'任务断点需要整组迁移，请打开详情操作。',workstream_has_related_tasks:'此任务有关联父任务或子任务，暂不能单独迁移。请先在任务管理中核对关联关系。',workstream_lifecycle_managed_by_task:'任务断点的状态由任务管理维护，请到运行与经验看板管理任务。',managed_content_create_correction:'此内容由任务或经验生成，请新增补充资料。',invalid_rule_settings:'入库条件格式不正确，请检查 JSON 设置。',invalid_skill_format:'Skill 格式不完整，请保留文件头和 JSON 入库条件。',invalid_skill_frontmatter:'请保留 Skill 的 name 和 description。',identity_conflict:'目标项目已存在同一资料，请先核对重复内容。',alias_conflict:'别名已属于其他项目，请换一个别名。'};
  const state = {view:'projects',project:'__all__',q:'',status:'',type:'',page:1,queue:'all',rows:[],selected:new Set(),projects:[],rules:null,total:0};
  let toastTimer, renderSequence=0;
  function toast(message) { $('#toast').textContent=message; $('#toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').hidden=true,6500); }
  async function api(route, body) {
    const response=await EvolvAuth.fetch('/api/knowledge/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
    const result=await response.json();
    if(!response.ok || result.ok===false) throw new Error(errors[result.error] || result.error || '操作失败，请重试。');
    return result;
  }
  function projectName(id) { return state.projects.find(p=>p.project===id)?.display_name || id || '未归属'; }
  function projectOptions(value='__all__', filters=false) {
    return (filters?'<option value="__all__">所有项目</option>':'<option value="">未归属 · 待确认</option>')+`<option value="__global__" ${value==='__global__'?'selected':''}>全局知识</option>`+(filters?`<option value="__none__" ${value==='__none__'?'selected':''}>未归属</option>`:'')+state.projects.filter(p=>p.status==='active'||p.status==='unregistered').map(p=>`<option value="${esc(p.project)}" ${p.project===value?'selected':''}>${esc(p.display_name||p.project)}</option>`).join('');
  }
  function typeOptions(value='', all=true) { return (all?'<option value="">全部类型</option>':'')+Object.entries(types).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join(''); }
  function badge(row) {return `<span class="badge ${row.status==='active'?'green':row.status==='candidate'?'amber':''}">${statuses[row.status]||esc(row.status)}</span>`;}
  function reason(row) {if(row.ingestion_reason)return row.ingestion_reason; if(row.ownership.excluded)return ({unresolved:'缺少明确归属',conflict:'归属线索冲突',unreviewed:'旧资料尚未核对归属',pending:'归属待确认',rejected:'归属已拒绝'})[row.ownership.state]||'归属需要核对'; return row.status==='candidate'?'等待核对资料与来源':'';}
  function route(view,project) { if(project!==undefined)state.project=project; state.page=1;state.selected.clear();if(location.hash==='#'+view)render();else location.hash=view; }
  function modal(title,body,footer='') {$('#dialog-content').innerHTML=`<div class="dialog-header"><h2>${esc(title)}</h2><button class="quiet" data-action="close" aria-label="关闭">✕</button></div><div class="dialog-body">${body}</div>${footer?`<div class="dialog-footer">${footer}</div>`:''}`;if(!$('#dialog').open)$('#dialog').showModal();}
  function close(){$('#dialog').close();}
  async function refreshProjects(){const result=await api('projects');state.projects=result.projects;$('#pending-count').textContent=result.pending||'';return result;}
  async function render(){
    const seq=++renderSequence; $('#content').inert=true;
    try {
    state.view=location.hash.slice(1)||new URLSearchParams(location.search).get('view')||'projects';if(!['projects','library','intake','rules','skill'].includes(state.view))state.view='projects';
    document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===state.view));
    $('#page-title').textContent=({projects:'项目知识库',library:'资料管理',intake:'入库与整理',rules:'入库规则',skill:'管理 Skill'})[state.view];
    const info=await refreshProjects();if(seq!==renderSequence)return;
    if(state.view==='projects'){renderProjects(info);return;}
    if(['rules','skill'].includes(state.view)){state.rules=await api('rules');if(seq!==renderSequence)return;renderRules();return;}
    const params=new URLSearchParams({project:state.project,q:state.q,status:state.status,content_type:state.type,page:state.page});
    if(state.view==='intake')params.set('queue',state.queue);
    const result=await api('items?'+params);if(seq!==renderSequence)return;
    state.rows=result.items;state.total=result.total;state.selected.clear();renderLibrary(result);
    } finally {if(seq===renderSequence)$('#content').inert=false;}
  }
  function renderProjects(info){
    $('#content').innerHTML=`<p class="intro">按项目组织资料，让每一条知识都有归处。查看来源、修正归属，也让 AI 按你的规则持续整理。</p><div class="stats"><div class="stat"><span>项目空间</span><strong>${info.projects.length}<small>独立组织资料</small></strong></div><div class="stat"><span>知识资料</span><strong>${info.total}<small>包含候选与归档</small></strong></div><div class="stat"><span>需要你确认</span><strong>${info.pending}<small>归属或入库待核对</small></strong></div></div><div class="section-head"><h2>我的项目</h2><button class="write" data-action="project-new">＋ 添加项目</button></div><div class="project-grid">${info.projects.map(p=>`<article class="project-card"><div class="project-head"><div class="project-icon">${esc((p.display_name||p.project).slice(0,1).toUpperCase())}</div><button class="quiet write" data-action="project-edit" data-project="${esc(p.project)}" aria-label="编辑 ${esc(p.display_name||p.project)}">···</button></div><h3><a href="#library" data-action="open-project" data-project="${esc(p.project)}">${esc(p.display_name||p.project)}</a></h3><p>${esc(p.aliases.length?p.aliases.join(' · '):p.project)}</p><div class="project-bottom"><a href="#library" data-action="open-project" data-project="${esc(p.project)}">${p.total} 份资料 →</a>${p.pending?`<a href="#intake" data-action="project-queue" data-project="${esc(p.project)}" class="badge amber">${p.pending} 待确认</a>`:'<span class="badge green">已整理</span>'}</div></article>`).join('')}<article class="project-card"><div class="project-icon">◎</div><h3><a href="#library" data-action="open-project" data-project="__global__">全局知识</a></h3><p>跨项目的偏好、通用约定与个人资料</p><div class="project-bottom"><a href="#library" data-action="open-project" data-project="__global__">查看全局资料 →</a></div></article><article class="project-card"><div class="project-icon">?</div><h3><a href="#intake" data-action="project-queue" data-project="__none__">未归属资料</a></h3><p>保留原始内容与来源，等待明确归属</p><div class="project-bottom"><a href="#intake" data-action="project-queue" data-project="__none__">核对并归入项目 →</a></div></article></div>`;
  }
  function renderLibrary(result){
    const intake=state.view==='intake';
    $('#content').innerHTML=`<p class="intro">${intake?'明确资料按当前规则自动入库；疑难资料保留在这里。选择资料可先预览整理结果，核对原因后处理。':'在一个地方查看和管理所有项目的资料。支持搜索全文、编辑内容、调整归属和入库状态。'}</p><div class="toolbar"><input id="search" type="search" placeholder="搜索标题、正文或关键词…" aria-label="搜索资料" value="${esc(state.q)}"><select id="filter-project" aria-label="筛选项目">${projectOptions(state.project,true)}</select><select id="filter-type" aria-label="筛选资料类型">${typeOptions(state.type)}</select>${intake?`<select id="filter-queue" aria-label="待确认类别"><option value="all">全部待确认</option><option value="candidate" ${state.queue==='candidate'?'selected':''}>等待入库</option><option value="ownership" ${state.queue==='ownership'?'selected':''}>归属待确认</option></select>`:`<select id="filter-status" aria-label="筛选资料状态"><option value="">当前资料</option>${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${k===state.status?'selected':''}>${v}</option>`).join('')}</select>`}<button data-action="search">搜索</button></div><div class="section-head"><h2>${state.project==='__all__'?(intake?'待确认资料':'全部资料'):state.project==='__none__'?'未归属资料':state.project==='__global__'?'全局知识':esc(projectName(state.project))} <span class="hint">${result.total} 份</span></h2>${intake?'<button class="write" data-action="organize-page">预览本页整理</button>':''}</div><div id="selection" class="selection" hidden></div>${result.items.length?`<div class="table-wrap"><table><thead><tr><th class="check"><input id="select-all" type="checkbox" aria-label="选择本页全部资料"></th><th>资料 / 来源线索</th><th>所属项目</th><th>类型</th><th>状态</th></tr></thead><tbody>${result.items.map(row=>`<tr><td class="check"><input type="checkbox" data-select="${row.id}" aria-label="选择资料 ${row.id}"></td><td><button class="item-link" data-action="detail" data-id="${row.id}">${esc(row.title)}</button><div class="excerpt">${esc(row.body)}</div>${intake&&reason(row)?`<div class="reason">${esc(reason(row))}</div>`:''}</td><td>${esc(row.project?projectName(row.project):row.scope==='global'?'全局知识':'未归属')}${row.ownership.excluded?'<div class="reason">归属待确认</div>':''}</td><td><span class="badge">${types[row.content_type]||esc(row.content_type)}</span></td><td>${badge(row)}<div class="hint" style="margin-top:8px">${esc(row.updated_at?.slice(0,10))}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">这里暂时没有资料<br>可以调整筛选条件，或新增一份资料。</div>'}<div class="pagination"><span>共 ${result.total} 份 · 第 ${state.page} / ${Math.max(1,Math.ceil(result.total/result.page_size))} 页</span><div class="actions"><button data-action="prev" ${state.page===1?'disabled':''}>上一页</button><button data-action="next" ${state.page*result.page_size>=result.total?'disabled':''}>下一页</button></div></div>`;
  }
  function selection(){const box=$('#selection');box.hidden=!state.selected.size;box.innerHTML=`<span>已选 ${state.selected.size} 份资料</span><button class="write" data-action="batch-assign">更改归属</button><button class="write" data-action="batch-publish">确认入库</button><button class="write" data-action="organize-selected">预览整理</button><button class="write" data-action="batch-archive">归档</button>`;}
  function projectEditor(project){const p=state.projects.find(x=>x.project===project);modal(p?'项目设置':'添加项目',`<div class="field"><label for="project-id">项目标识</label><input id="project-id" value="${esc(p?.project)}" ${p?'readonly':''} placeholder="例如 eva、evolvmem"><small>使用稳定的英文标识，便于 AI 判断归属。</small></div><div class="field"><label for="project-name">显示名称</label><input id="project-name" value="${esc(p?.display_name)}" placeholder="例如 EVA 智能客服"></div><div class="field"><label for="project-aliases">业务别名</label><textarea id="project-aliases" placeholder="每行一个，例如：智能客服">${esc(p?.aliases.join('\n'))}</textarea><small>名称与别名会参与资料归属判断，请避免含糊的通用词。</small></div>`,`<button data-action="close">取消</button><button class="primary write" data-action="project-save">保存项目</button>`);}
  let editing=null, proposalIds=[];
  function newItem(seed={}){editing=null;const project=seed.project??(state.project.startsWith('__')?'':state.project);modal('新增知识资料',`${seed.source?`<div class="rule-note">${esc(seed.source)}</div>`:''}<div class="field"><label for="item-title">资料标题</label><input id="item-title" maxlength="200" value="${esc(seed.title)}" placeholder="给资料一个便于查找的名称"></div><div class="form-grid"><div class="field"><label for="item-project">所属项目</label><select id="item-project">${projectOptions(project)}</select></div><div class="field"><label for="item-type">资料类型</label><select id="item-type">${typeOptions('reference',false).replace(/<option value="(workstream_checkpoint|project_summary)".*?<\/option>/g,'')}</select></div></div><div class="field"><label for="item-body">资料正文</label><textarea class="body" id="item-body" placeholder="粘贴文本或 Markdown，保留业务规则、依据与适用条件。">${esc(seed.body)}</textarea><div class="actions"><label class="hint" for="import-file">或导入文本 / Markdown</label><input id="import-file" type="file" accept=".txt,.md,.markdown,text/plain,text/markdown"></div></div><div class="field"><label for="item-source">来源说明</label><input id="item-source" value="${esc(seed.source||'用户录入')}" placeholder="会话、文件名称或原文链接"></div><div class="hint">按规则处理会立即判断：明确资料入库，疑难资料进入待确认。</div>`,`<button data-action="create-draft">保存到待确认</button><button class="primary write" data-action="create-auto">按规则处理</button>`);}
  async function detail(id){editing=await api('items/'+id);const r=editing;modal('资料详情',`<div class="meta-line">${badge(r)}<span class="badge">${types[r.content_type]}</span><span class="hint">编号 ${r.id} · ${esc(r.updated_at?.slice(0,10))}</span></div><div class="field"><label for="item-title">资料标题</label><input id="item-title" value="${esc(r.title)}" maxlength="200"></div><div class="form-grid"><div class="field"><label for="item-project">项目归属</label><select id="item-project">${projectOptions(r.project|| (r.scope==='global'?'__global__':''))}</select></div><div class="field"><label>归属操作</label><button class="write" data-action="assign">确认 / 更改归属</button><small>${r.workstream_id?'变更将整组迁移任务和历史断点。':'人工确认会优先于自动判断。'}</small></div></div>${reason(r)?`<div class="rule-note">${esc(reason(r))}</div>`:''}<div class="field"><label for="item-body">正文</label><textarea class="body" id="item-body" ${r.managed_content?'readonly':''}>${esc(r.body)}</textarea>${r.managed_content?'<small>这是系统生成的任务、摘要或结构化经验。内容随来源更新；可新增补充资料记录更正。</small><button class="write" data-action="correction">新增补充 / 更正资料</button>':''}</div><div class="field"><label for="item-tags">标签</label><input id="item-tags" value="${esc(r.tags.join('，'))}" placeholder="用逗号分隔"></div><div class="section-head"><h3>原始来源</h3><span class="hint">${r.sources.length} 条关联</span></div>${r.sources.map(s=>`<div class="source">${esc(s.source_ref||s.source_kind)}<small>${esc(s.adapter||s.source_kind)} · ${esc(s.created_at)}${s.source_project?' · '+esc(s.source_project):''}</small></div>`).join('')||'<p class="hint">旧记录没有关联原始来源，确认前请核对正文。</p>'}${r.rule_revision?`<p class="version">处理规则版本 ${esc(r.rule_revision.slice(0,12))}</p>`:''}`,`<button class="danger write" data-action="item-delete">删除</button>${r.status==='active'?'<button class="write" data-action="item-archive">归档</button>':r.status==='candidate'?'<button class="write" data-action="item-reject">暂不入库</button><button class="write" data-action="item-publish">确认入库</button>':'<button class="write" data-action="item-restore">恢复入库</button>'}<button class="primary write" data-action="item-save">保存内容</button>`);}
  function renderRules(){const r=state.rules,s=r.settings;
    if(state.view==='skill'){$('#content').innerHTML=`<p class="intro">这是 AI 读取的知识库管理 Skill。说明文字与可执行入库条件保存在同一份文件中，保存后用于后续提炼和整理。</p><section class="panel"><div class="section-head" style="margin-top:0"><div><h2>SKILL.md</h2><p class="version">当前版本 ${r.revision.slice(0,12)}</p></div><div class="actions"><button data-action="skill-download">下载文件</button><button class="write" data-action="rule-reset">恢复默认</button><button class="primary write" data-action="skill-save">保存 Skill</button></div></div><textarea id="skill-text" class="code skill-editor" aria-label="管理 Skill 内容" spellcheck="false">${esc(r.skill)}</textarea><p>请保留文件头与 JSON 条件。修改自然语言说明会影响 AI 的提炼；明确的阈值、忽略词与项目覆盖由入库程序执行。</p></section>`;return;}
    $('#content').innerHTML=`<p class="intro">你决定什么值得保留、归入哪个项目，以及什么时候需要确认。保存后立即作用于后续处理；历史资料可在“入库与整理”中按新规则重新整理。</p><div class="two-columns"><section class="panel"><div class="section-head" style="margin-top:0"><h2>默认入库逻辑</h2><span class="badge purple">明确自动 · 疑难确认</span></div><div class="rule-note">唯一项目线索 + 可核对来源 + 达到质量门槛 → 自动入库。<br>多项目冲突、来源不足或经验缺少证据 → 待确认。</div><div class="form-grid"><div class="field"><label for="min-confidence">最低置信度（0–1）</label><input id="min-confidence" type="number" min="0" max="1" step="0.05" value="${s.auto_min_confidence}"></div><div class="field"><label for="require-source">来源要求</label><select id="require-source"><option value="true" ${s.require_source?'selected':''}>需要可核对的来源</option><option value="false" ${!s.require_source?'selected':''}>不强制要求来源</option></select></div><div class="field"><label for="min-chars">正文最少字数</label><input id="min-chars" type="number" min="1" value="${s.min_chars}"></div><div class="field"><label for="max-chars">正文最多字数</label><input id="max-chars" type="number" min="1" max="100000" value="${s.max_chars}"></div></div><div class="field"><label for="ignore-keywords">忽略关键词</label><textarea id="ignore-keywords" placeholder="每行一个关键词；命中的新资料不进入正式知识库">${esc(s.ignore_keywords.join('\n'))}</textarea></div><div class="field"><label for="project-overrides">项目专属条件（JSON）</label><textarea class="code" id="project-overrides" spellcheck="false">${esc(JSON.stringify(s.project_overrides,null,2))}</textarea><small>例：{"eva": {"auto_min_confidence": 0.95}}。未配置的项目沿用默认规则。</small></div><div class="field"><label for="rule-instructions">AI 整理说明</label><textarea id="rule-instructions" style="min-height:260px">${esc(r.instructions)}</textarea><small>描述业务判断、来源优先级、保留范围及例外。这些说明会传给 AI 阅读。</small></div><div class="actions"><button class="primary write" data-action="rules-save">保存并生效</button><span class="version">版本 ${r.revision.slice(0,12)}</span></div></section><section class="panel"><h2>试一份资料</h2><p>使用当前已保存的规则预览，不会写入知识库。</p><div class="field"><label for="sample-title">标题</label><input id="sample-title" placeholder="例如 EVA 客服退款规则"></div><div class="field"><label for="sample-body">正文</label><textarea id="sample-body" placeholder="输入包含项目线索的资料内容…"></textarea></div><div class="form-grid"><div class="field"><label for="sample-confidence">资料置信度</label><input id="sample-confidence" type="number" min="0" max="1" step="0.05" value="0.9"></div><div class="field"><label for="sample-source">来源</label><input id="sample-source" value="规则预览样例"></div></div><button data-action="rule-preview">预览判断结果</button><div id="preview-result" hidden class="preview-result"></div><div class="divider"></div><h3>归属如何识别</h3><p>检查资料中的项目名称、显示名称、别名和明确项目标识。多个项目线索发生冲突时留待确认。你可以在项目设置中维护业务别名。</p><a class="hint" href="#skill">查看完整管理 Skill →</a></section></div>`;
  }
  function selectedItems(){return state.rows.filter(r=>state.selected.has(r.id)).map(r=>({id:r.id,expected_revision:r.revision}));}
  async function batch(action,extra={}){const result=await api('batch',{action,items:selectedItems(),...extra});close();await render();toast(`已处理 ${result.succeeded} 份${result.failed?'；'+result.failed+' 份未处理：'+result.items.filter(r=>!r.ok).map(r=>errors[r.error]||r.error).join('；'):''}`);}
  async function organize(ids,apply=false){proposalIds=ids;const result=await api('organize',{ids,apply});modal(apply?'整理完成':'整理结果预览',`<div class="rule-note">${apply?`已自动入库 ${result.applied} 份，忽略归档 ${result.ignored} 份，${result.pending} 份仍需确认。`:'仅处理项目明确且符合当前规则的资料。人工决定和系统生成资料会保留，疑难资料继续待确认。'}</div><div class="proposals">${result.items.map(p=>`<div class="proposal"><strong>${esc(p.title)}</strong><p><span class="badge ${p.action==='auto'?'green':'amber'}">${p.applied?(p.action==='ignore'?'已归档':'已入库'):p.action==='auto'?'可自动入库':p.action==='ignore'?'不入库':'待确认'}</span> ${esc(p.project?projectName(p.project):'未确定项目')}</p><p>${esc(p.reason)}</p></div>`).join('')}</div>`,apply?'<button class="primary" data-action="close">完成</button>':`<button data-action="close">取消</button><button class="primary write" data-action="organize-apply" ${!result.items.some(p=>['auto','ignore'].includes(p.action))?'disabled':''}>按当前规则整理明确资料</button>`);if(apply)await render();}
  const actions={
    close, 'project-new':()=>projectEditor(), 'project-edit':b=>projectEditor(b.dataset.project),
    'open-project':b=>route('library',b.dataset.project), 'project-queue':b=>route('intake',b.dataset.project),
    search:()=>{state.q=$('#search').value;state.page=1;return render();},prev:()=>{state.page--;return render();},next:()=>{state.page++;return render();},
    'project-save':async()=>{await api('projects',{project:$('#project-id').value.trim(),display_name:$('#project-name').value.trim(),aliases:$('#project-aliases').value.split('\n').map(s=>s.trim()).filter(Boolean)});close();await render();toast('项目与别名已保存');},
    detail:b=>detail(Number(b.dataset.id)),
    'create-auto':()=>create('auto'),'create-draft':()=>create('draft'),
    'item-save':async()=>{const r=await api(`items/${editing.id}/update`,{expected_revision:editing.revision,title:$('#item-title').value,body:$('#item-body').value,tags:$('#item-tags').value.split(/[,，]/).map(s=>s.trim()).filter(Boolean)});await render();await detail(r.id);toast('资料内容已保存');},
    assign:async()=>{const p=$('#item-project').value;if(!p)throw new Error('请选择项目或全局知识。');if(editing.workstream_id&&!confirm('将迁移整个任务及其全部历史断点到所选项目。确认继续？'))return;await api(`items/${editing.id}/assign`,{expected_revision:editing.revision,project:p==='__global__'?'':p,move_workstream:!!editing.workstream_id});await render();await detail(editing.id);toast('项目归属已确认');},
    correction:()=>newItem({project:editing.project,title:'补充：'+editing.title,source:`对知识资料 #${editing.id} 的补充 / 更正`}),
    'batch-assign':()=>modal('批量更改归属',`<p class="intro" style="margin-top:20px">已选择 ${state.selected.size} 份资料。任务断点请在详情中整组迁移。</p><div class="field"><label for="batch-project">目标项目</label><select id="batch-project">${projectOptions('')}</select></div>`,'<button data-action="close">取消</button><button class="primary write" data-action="batch-assign-save">确认更改</button>'),
    'batch-assign-save':()=>{const p=$('#batch-project').value;if(!p)throw new Error('请选择目标项目。');return batch('assign',{project:p==='__global__'?'':p});},
    'batch-publish':()=>batch('publish'),'batch-archive':()=>batch('archive'),
    'organize-selected':()=>organize([...state.selected]),'organize-page':()=>organize(state.rows.map(r=>r.id)), 'organize-apply':()=>organize(proposalIds,true),
    'rules-save':async()=>{const settings={auto_min_confidence:Number($('#min-confidence').value),require_source:$('#require-source').value==='true',min_chars:Number($('#min-chars').value),max_chars:Number($('#max-chars').value),ignore_keywords:$('#ignore-keywords').value.split('\n').map(s=>s.trim()).filter(Boolean),project_overrides:JSON.parse($('#project-overrides').value)};state.rules=await api('rules',{expected_revision:state.rules.revision,settings,instructions:$('#rule-instructions').value});renderRules();toast('入库规则已生效，后续处理会读取新版本');},
    'skill-save':async()=>{state.rules=await api('rules',{expected_revision:state.rules.revision,skill:$('#skill-text').value});renderRules();toast('管理 Skill 已保存，与入库规则共用同一来源');},
    'rule-reset':async()=>{if(!confirm('将完整 Skill 和入库条件恢复为默认内容，确认继续？'))return;state.rules=await api('rules',{expected_revision:state.rules.revision,reset:true});renderRules();toast('已恢复默认规则');},
    'skill-download':()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('#skill-text').value],{type:'text/markdown;charset=utf-8'}));a.download='SKILL.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},
    'rule-preview':async()=>{const r=await api('preview',{title:$('#sample-title').value,body:$('#sample-body').value,confidence:Number($('#sample-confidence').value),source:$('#sample-source').value});$('#preview-result').hidden=false;$('#preview-result').textContent=`${({auto:'自动入库',review:'待确认',ignore:'不入库'})[r.action]}\n项目：${r.project?projectName(r.project):r.scope==='global'?'全局知识':'未确定'}\n原因：${r.reason}\n规则版本：${r.rule_revision.slice(0,12)}`;}
  };
  async function create(action){const p=$('#item-project').value;const row=await api('items',{title:$('#item-title').value,body:$('#item-body').value,source:$('#item-source').value,content_type:$('#item-type').value,project:p==='__global__'?'':p,scope:p==='__global__'?'global':'project',action});close();await render();toast(row.status==='active'?'资料已入库':row.status==='archived'?'资料未入库，已归档：'+row.ingestion_reason:'资料已保存到待确认');}
  ['archive','restore','publish','reject','delete'].forEach(action=>actions['item-'+action]=async()=>{if(action==='delete'&&!confirm('删除这份资料？删除后可在“已删除”筛选中找回。'))return;await api(`items/${editing.id}/transition`,{expected_revision:editing.revision,action});close();await render();toast('资料状态已更新');});
  document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b)return;event.preventDefault();const action=actions[b.dataset.action];if(!action)return;b.disabled=true;try{await action(b);}catch(error){toast(error.message);}finally{b.disabled=false;}});
  document.addEventListener('change',async event=>{const e=event.target;try{if(e.dataset.select){e.checked?state.selected.add(Number(e.dataset.select)):state.selected.delete(Number(e.dataset.select));selection();}else if(e.id==='select-all'){state.selected=e.checked?new Set(state.rows.map(r=>r.id)):new Set();document.querySelectorAll('[data-select]').forEach(x=>x.checked=e.checked);selection();}else if(e.id.startsWith('filter-')){state[({'filter-project':'project','filter-type':'type','filter-status':'status','filter-queue':'queue'})[e.id]]=e.value;state.page=1;await render();}else if(e.id==='import-file'&&e.files[0]){if(e.files[0].size>400000)throw new Error('文本文件过大，请使用不超过 100,000 字的资料。');$('#item-body').value=await e.files[0].text();if(!$('#item-title').value)$('#item-title').value=e.files[0].name.replace(/\.(txt|md|markdown)$/i,'');$('#item-source').value=e.files[0].name;}}catch(error){toast(error.message);}});
  document.addEventListener('input',e=>{if(e.target.id==='search')state.q=e.target.value;});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='search')actions.search().catch(x=>toast(x.message));});
  $('#new-item').onclick=()=>newItem();
  window.addEventListener('hashchange',()=>{state.page=1;state.status='';window.scrollTo(0,0);render().catch(e=>toast(e.message));});
  EvolvAuth.ready.then(()=>{document.body.classList.toggle('readonly',!EvolvAuth.canWrite);$('#readonly').hidden=EvolvAuth.canWrite;return render();}).catch(e=>{$('#content').innerHTML=`<div class="empty error">${esc(e.message)}</div>`;});
})();
