/* Stage-specific editing backed by the same policy consumed by ingestion. */
window.EvolvPipeline={async render({mount,api,esc,toast,onDirty,onBusy}) {
 const catalog=await api('skills');let active='ownership',dirty=false,busy=false;
 const $=s=>mount.querySelector(s),names={project_alias_matching:'按正文中的项目名称与别名匹配',ambiguous_project_names:'不参与匹配的通用词 · 每行一个',cleaning_drop_lines:'额外去除的固定提示行 · 完全匹配，每行一个',cleaning_collapse_duplicates:'合并相邻且内容相同的同角色消息',related_memory_projects:'允许对照旧知识的项目标识 · 每行一个',auto_min_confidence:'自动入库最低置信度',require_source:'要求可核对来源',min_chars:'正文最少字数',max_chars:'正文最多字数',ignore_keywords:'不入库关键词 · 每行一个',auto_explicit_rules:'明确且无冲突的协作规则自动更新'};
 const setDirty=v=>{dirty=v;onDirty(v);if($('#stage-state'))$('#stage-state').textContent=v?'有未保存的修改':'已保存';};
 mount.innerHTML=`<p class="intro">5 个 Skill 对应资料处理的 5 项职责。选择一项修改；保存后，后续处理读取新版本。</p><div class="pipeline-catalog">${catalog.skills.map((s,i)=>`<button data-pipeline-stage="${s.id}"><span>0${i+1}</span><strong>${esc(s.title)}</strong><small>${esc(s.description)}</small></button>`).join('')}</div><div id="stage-editor"></div><details class="panel"><summary>高级管理与旧版入口</summary><p>各环节共享同一份入库规则，协作框架沿用原有版本管理。</p><a href="#knowledge/rules" data-view="rules">完整入库条件与模型对比</a> · <a href="#knowledge/learning" data-view="learning">协作成果与版本恢复</a><div id="stage-full-skill"></div></details>`;
 function controls(s){return Object.entries(s.settings).map(([key,value])=>`<div class="field">${typeof value==='boolean'?`<label class="extraction-choice"><input type="checkbox" data-stage-setting="${key}" ${value?'checked':''}>${esc(names[key])}</label>`:`<label for="stage-${key}">${esc(names[key])}</label>${Array.isArray(value)?`<textarea id="stage-${key}" data-stage-setting="${key}">${esc(value.join('\n'))}</textarea>`:`<input id="stage-${key}" type="number" step="${key==='auto_min_confidence'?'0.05':'1'}" data-stage-setting="${key}" value="${value}">`}`}</div>`).join('');}
 function stage(){return catalog.skills.find(s=>s.id===active);}
 function payload(){const s=stage(),settings={};mount.querySelectorAll('[data-stage-setting]').forEach(e=>{const k=e.dataset.stageSetting,v=s.settings[k];settings[k]=typeof v==='boolean'?e.checked:Array.isArray(v)?e.value.split('\n').map(x=>x.trim()).filter(Boolean):Number(e.value);});return {expected_revision:s.revision,instructions:$('#stage-instructions').value,settings};}
 function messages(){const result=[];for(const line of $('#stage-sample').value.split('\n')){const m=line.match(/^(用户|助手|工具)[：:]\s*(.*)$/);if(m)result.push({role:({用户:'user',助手:'assistant',工具:'tool'})[m[1]],content:m[2]});else if(result.length)result.at(-1).content+='\n'+line;else if(line.trim())throw Error('请以“用户：”“助手：”或“工具：”标明角色。');}return result;}
 function draw(){const s=stage();mount.querySelectorAll('[data-pipeline-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pipelineStage===active)));
  $('#stage-editor').innerHTML=`<section class="panel"><div class="section-head"><div><h2>${esc(s.title)} Skill</h2><p class="hint">${esc(s.execution)} · 版本 ${esc(String(s.revision).slice(0,12))}</p></div><div class="actions"><span id="stage-state" role="status">已保存</span><button data-pipeline-action="download">下载已保存 Skill</button><button class="primary write" data-pipeline-action="save">保存本环节</button></div></div><div class="field"><label for="stage-instructions">AI 执行说明</label><textarea id="stage-instructions" class="stage-instructions">${esc(s.instructions)}</textarea><small>自然语言说明供 AI 处理时参考，下方条件由程序执行。原话依据、来源检查与疑难待确认仍然保留。</small></div><div class="form-grid">${controls(s)}</div>${active==='cleaning'?'<p class="rule-note">原话正文只做去噪；需求表达是引用原话的派生知识。保存影响新对话与后续提炼，已入库历史不会静默改写。</p>':''}
  ${['ownership','cleaning','extraction'].includes(active)?`<details class="skill-trial" open><summary>用样例检查效果</summary><div class="field"><label for="stage-sample">样例${active==='ownership'?'资料':'对话'}</label><textarea id="stage-sample">${active==='ownership'?'Evo 项目需要在经验问答里新增项目。':'用户：我想在经验里直接加项目，不要让我到处找。\n工具：这段工具记录应移除。\n助手：会把新增项目入口放在问答编辑处。'}</textarea></div><div class="field"><label for="stage-project">已确认项目${active==='ownership'?' · 可留空判断':''}</label><select id="stage-project"><option value="">${active==='ownership'?'自动判断':'请选择项目'}</option></select></div><div class="actions">${active==='ownership'?'<button data-pipeline-action="ownership-preview">预览归属判断</button>':`${active==='cleaning'?'<button data-pipeline-action="clean-preview">本地去噪预览</button>':''}<button class="write" data-pipeline-action="model-preview">对比需求与问答提炼</button>`}</div><p class="hint">${active==='ownership'?'本地预览草稿匹配条件，不保存资料。':'本地去噪不调用模型。点击“对比”才发送此处样例给已配置模型（最多 2 次）；默认不发送旧记忆，不保存资料。'}</p><div id="stage-result" role="status"></div></details>`:''}</section>`;
  if($('#stage-project'))api('projects').then(r=>{if($('#stage-project'))r.projects.filter(p=>p.status==='active').forEach(p=>{const o=new Option(p.display_name||p.project,p.project);$('#stage-project').add(o);});}).catch(e=>toast(e.message));
 }
 async function fullSkill(){const r=await api('rules');$('#stage-full-skill').innerHTML=`<details><summary>完整管理 SKILL.md</summary><textarea id="skill-text" class="code skill-editor" aria-label="管理 Skill 内容">${esc(r.skill)}</textarea><div class="actions"><button data-pipeline-action="full-download">下载文件</button><button class="write" data-pipeline-action="full-save">保存完整 Skill</button></div></details>`;$('#stage-full-skill').dataset.revision=r.revision;}
 const download=(text,name)=>{const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 mount.oninput=e=>{if(['stage-instructions','skill-text'].includes(e.target.id)||e.target.hasAttribute('data-stage-setting'))setDirty(true);};mount.onchange=e=>{if(e.target.hasAttribute('data-stage-setting'))setDirty(true);};
 mount.onclick=async e=>{const tab=e.target.closest('[data-pipeline-stage]'),b=e.target.closest('[data-pipeline-action]');if((!tab&&!b)||busy)return;e.preventDefault();
  if(tab){if(dirty&&!confirm('有未保存的修改，放弃并切换 Skill？'))return;active=tab.dataset.pipelineStage;setDirty(false);draw();await fullSkill();return;}
  busy=true;b.disabled=true;onBusy(true);
  try{const action=b.dataset.pipelineAction;
   if(action==='save'){const saved=await api('skills/'+active,payload());catalog.skills=(await api('skills')).skills;setDirty(false);draw();await fullSkill();toast(saved.title+' Skill 已保存，后续处理读取新版本');}
   else if(action==='download')download(stage().skill,'SKILL.md');
   else if(action==='full-download')download($('#skill-text').value,'SKILL.md');
   else if(action==='full-save'){await api('rules',{expected_revision:$('#stage-full-skill').dataset.revision,skill:$('#skill-text').value});catalog.skills=(await api('skills')).skills;setDirty(false);draw();await fullSkill();toast('完整管理 Skill 已保存');}
   else if(action==='clean-preview'){const r=await api('skills/cleaning/preview',{...payload(),messages:messages()});$('#stage-result').innerHTML=`<h3>去噪结果</h3><p>${r.input_messages} 轮 → ${r.dialogue_messages} 轮；模型调用 0 次，入库 0 条。</p><pre class="project-memory-text">${esc(r.text)}</pre>`;}
   else {const current=await api('rules'),draft=payload();if(current.revision!==draft.expected_revision)throw Error('规则已变化，请重新打开本环节。');const field=active==='ownership'?'ownership_instructions':active==='cleaning'?'cleaning_instructions':'extraction_instructions';const rules={expected_revision:current.revision,settings:{...current.settings,...draft.settings,[field]:draft.instructions}};
    if(action==='ownership-preview'){const r=await api('preview',{body:$('#stage-sample').value,project:$('#stage-project').value,source:'Skill 样例',rules});$('#stage-result').innerHTML=`<h3>${esc(({auto:'明确，可入库',review:'待确认',ignore:'不入库'})[r.action])}</h3><p>项目：${esc(r.project||'未确定')} · ${esc(r.reason)}</p>`;}
    else {if(!$('#stage-project').value)throw Error('请先选择样例所属项目。');$('#stage-result').textContent='正在比较提炼结果…';const r=await api('extraction/preview',{project:$('#stage-project').value,messages:messages(),rules});$('#stage-result').innerHTML=`<p>模型调用 ${r.model_calls} 次；入库 0 条。草稿只用于本次对比，保存后才正式生效。</p><div class="extraction-comparison">${[['已保存规则',r.current],['当前草稿',r.draft]].map(([title,v])=>`<section><h3>${title}</h3><details><summary>去噪后的对话</summary><pre class="project-memory-text">${esc(v.cleaned_messages.map(m=>(m.role==='user'?'用户：':'AI：')+m.content).join('\n\n'))}</pre></details>${v.candidates.map(c=>`<article class="extraction-candidate"><span class="badge">${c.status==='active'?'自动入库':'待确认'}</span><p>${esc(c.body)}</p><p class="hint">${esc(c.reason)}</p>${EvolvExtraction.process(c,esc)}</article>`).join('')||'<p>未提炼出需要保存的知识。</p>'}</section>`).join('')}</div>`;}
   }
  }catch(error){toast(error.message);if($('#stage-result'))$('#stage-result').textContent=error.message;}finally{busy=false;b.disabled=false;onBusy(false);}
 };draw();await fullSkill();
}};
